routes/frontend.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\AmbulanceController;
use App\Http\Controllers\BloodBankController;
use App\Http\Controllers\PoliceStationController;
use App\Models\BloodBank;
use App\Models\Contact;

/* 
/ ------------------------------------------------------------------------
/ Frontend Web Routes Start
/ ------------------------------------------------------------------------
*/

Route::get('/', function () {
    $totalMembers = User::count();
    $donars = BloodBank::count();
    $contacts = Contact::count();
    return view('frontend', compact('totalMembers', 'donars', 'contacts'));
});
Route::get('/contact-us', function () {
    return view('frontend.contact-us');
});

Route::post('sendmail', [ContactController::class, 'sendMail'])->name('sendMail');
Route::get('/contacts', [ContactController::class, 'index'])->name('contact.index');
Route::post('/store', [ContactController::class, 'store'])->name('contact.store');
Route::post('/delete/{id}', [ContactController::class, 'destroy'])->name('contact.delete');


Route::get('/law', function () {
    return view('frontend.law');
});
Route::prefix('services')->group(function () {

    Route::get('/police-stations', [PoliceStationController::class, 'getPoliceStationService']);
    Route::get('/police-stations/{division}', [PoliceStationController::class, 'divisionCategory']);
    Route::get('/get-district', [PoliceStationController::class, 'getDistrict']);
    Route::get('/get-area', [PoliceStationController::class, 'getArea']);
    
    Route::get('/ambulances', [AmbulanceController::class, 'getAmbulanceService']);
    Route::get('/ambulances/{division}', [AmbulanceController::class, 'divisionCategory']);
    Route::get('/blood-bank', [BloodBankController::class, 'getBloodBankService']);
    Route::get('/blood-banks/{division}', [BloodBankController::class, 'divisionCategory']);

    Route::get('/location', [ServicesController::class, 'getGeoLocation']);

    Route::get('/picture-records', function () {
        return view('frontend.services.picture-record');
    });

});

routes/web.php
<?php

use App\Models\User;
use App\Models\Contact;
use App\Models\BloodBank;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\AmbulanceController;
use App\Http\Controllers\BloodBankController;
use App\Http\Controllers\EmergencyController;
use App\Http\Controllers\PictureRecordController;
use App\Http\Controllers\PoliceStationController;
use App\Models\Ambulance;

include('frontend.php');
/* 
/ ------------------------------------------------------------------------
/ Frontend Web Routes End
/ ------------------------------------------------------------------------
*/
Auth::routes(); //[Comments] laravel ui authenticate login routes

Route::middleware(['auth'])->group(function () {
    
    Route::get('/users', [ProfileController::class, 'userList'])->name('users');
    Route::get('/users/edit/{id}', [ProfileController::class, 'userEdit'])->name('user.edit');
    Route::get('profile', [ProfileController::class, 'profile'])->name('profile');
    Route::post('/users/update/{id}', [ProfileController::class, 'userUpdate'])->name('user.update');
    Route::post('update-profile', [ProfileController::class, 'updateProfile'])->name('update-profile');
    Route::post('/destroy/{id}', [ProfileController::class, 'userRemove'])->name('user.destroy');

    /* 
    / ------------------------------------------------------------------------
    / Backend Web Routes Start
    / ------------------------------------------------------------------------
    */

    Route::get('/dashboard', function () {
        $totalMembers = User::count();
        $donars   = BloodBank::count();
        $contacts = Contact::count();
        $ambulances = Ambulance::count();
        return view('backend.dashboard', compact('totalMembers', 'donars', 'contacts', 'ambulances'));
    });

    Route::get('/index', function () {
        return view('backend.application.index');
    });

    Route::resource('locations', LocationController::class);
    Route::resource('police-stations', PoliceStationController::class);
    Route::resource('ambulances', AmbulanceController::class);
    Route::resource('blood-banks', BloodBankController::class);
    
});

Route::post('/emergency-alerts', [EmergencyController::class, 'sendAlert'])->name('emergency-alert');
Route::resource('picture-records', PictureRecordController::class)->except([
    'create', 'show', 'edit', 'update'
]);;

Route::get('locations/{latitude}/{longitude}/{accuracy}', [LocationController::class, 'shareLocation'])->name('share-location');

Route::get('/send-sms', function () {
  
        $sid = "AC1532d12dedb3bb7ec4875aecd73977d6"; // Your Account SID from www.twilio.com/console
        $token = "7331206ec49b58678eba7d77f3f59b97"; // Your Auth Token from www.twilio.com/console

        $client = new Twilio\Rest\Client($sid, $token);
        $message = $client->messages->create(
        '+8801811925439', // Text this number
        [
            'from' => '+18704744277', // From a valid Twilio number
            'body' => 'Hello from Twilio! Prabir'
        ]
        );

    echo  $message->sid;
});





/* 
/ ------------------------------------------------------------------------
/ Backend Web Routes End
/ ------------------------------------------------------------------------
*/



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Ambulance.php
<?php

namespace App\Models;

use App\Models\Location;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Ambulance extends Model
{
    use HasFactory;
    protected $table = "ambulances";
    protected $guarded = [];

    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    protected static function ambulanceType()
    {
        return [
             'AC'
            ,'Non-AC'
            ,'Fridger'
            ,'Corpse Carrier'
        ];
    }

}

app/Http/Controllers/AmbulanceController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\Location;
use App\Models\Ambulance;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;

class AmbulanceController extends Controller
{
    public function index()
    {
        $ambulances = Ambulance::orderBy('location_id', 'asc')->get();
        return view('backend.ambulances.index', compact('ambulances'));
    }
    public function create()
    {
        $types = Ambulance::ambulanceType();
        $location = Location::all();
        return view('backend.ambulances.create', compact('location', 'types'));
    }
    public function store(Request $request)
    {
        try {
            Ambulance::create($request->all());
            
            return redirect()->route('ambulances.index')->with('alert', 'Saved Successfully');
        } 
        catch (Exception $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
    }
    public function show($id)
    {
        $data = Ambulance::where('id', $id)->first();
        return view('backend.ambulances.show', compact('data'));
    }
    public function edit($id)
    {
        $location = Location::all();
        $types = Ambulance::ambulanceType();
        $data = Ambulance::where('id', $id)->first();
        return view('backend.ambulances.edit', compact('data', 'location', 'types'));
    }
    public function update(Request $request, $id)
    {
        try {
            $ambulance = Ambulance::where('id', $id)->first();
            $ambulance->update($request->all());

            return redirect()->route('ambulances.index')->with('alert', 'Updated Successfully');
        } 
        catch (Exception $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
    }
    public function destroy($id)
    {
        try {
            $data = Ambulance::where('id', $id)->first();
            $data->delete();
            return redirect()->route('ambulances.index')->with('alert', 'Deleted Successfully');
        } 
        catch (Exception $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
    }
    /**
     * FRONTEND INTEGRATION
     */
    public function getAmbulanceService(Request $request)
    {
        try {
            $selectedLocation = $request->location_id ?? null;

            if (isset($request->location_id)) {
                $ambulances = Ambulance::where('location_id', $request->location_id)->get();
            } else {
                $ambulances = Ambulance::all();
            }
            $locations = Location::orderBy('division', 'asc')->get();

            $ambulanceLocationIds = Ambulance::pluck('location_id')->toArray();
            $categories = Location::whereIn('id', $ambulanceLocationIds)->orderBy('division')->get()->groupBy('division');

            return view('frontend.services.ambulance', compact('ambulances', 'locations', 'selectedLocation', 'categories'));
            
        } 
        catch (Exception $th) {
            return redirect()->back()->withErrors($th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->withErrors($th->getMessage());
        }
    }
    public function divisionCategory($division)
    {
        $locationIds = Location::where(DB::raw(trim('lower(division)', ' ')), 'like', '%' . strtolower($division) . '%')->pluck('id')->toArray();
        $ambulances = Ambulance::whereIn('location_id', $locationIds)->get();
        $locations = Location::orderBy('division', 'asc')->get();
        $ambulanceIds = Ambulance::pluck('location_id')->toArray();
        $categories = Location::whereIn('id', $ambulanceIds)->orderBy('division')->get()->groupBy('division');
        return view('frontend.services.ambulance', compact('ambulances', 'categories', 'locations'));
    }

}

resources/views/backend/ambulances/create.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="container-fluid">  
    <div class="card">
        <div class="card-header">
            <div class="text-center">
                <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Ambulances</span>
            </div>
            <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('ambulances.index')}}">
                <span class="mdi mdi-playlist-plus"> List</span>
            </a>
        </div>
        <div class="card-body">
            <form style="margin-left: 10px" class="form-horizontal" action="{{ route('ambulances.store') }}" role="form" method="post">
                @csrf 
                <div class="form-group row">
                    <label for="location" class="col-sm-2 pt-2">Locations</label>
                    <div class="col-sm-10">
                        <select name="location_id" class="form-control" required>
                            <option value="">Choose Location</option>
                            @isset($location)
                                @foreach ($location as $item)
                                    <option value="{{ $item->id }}">
                                        @if(isset($item->division))
                                            {{ isset($item) ? ($item->division.', '.$item->district.', '.$item->area) : null }}
                                        @else                                          
                                            {{ isset($item) ? ($item->district.', '.$item->area) : null }}
                                        @endif
                                    </option>
                                @endforeach
                            @endisset
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="organization_name" class="col-sm-2 pt-2">Organization Name</label>
                    <div class="col-sm-10">
                        <input type="text" id="organization_name" name="organization_name" class="form-control" placeholder="Enter Organization Name">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="driver_name" class="col-sm-2 pt-2">Driver Name</label>
                    <div class="col-sm-10">
                        <input type="text" id="driver_name" name="driver_name" class="form-control" placeholder="Enter Driver Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="driver_number" class="col-sm-2 pt-2">Organization Number</label>
                    <div class="col-sm-10">
                        <input type="number" id="driver_number" name="driver_number" class="form-control" placeholder="Enter Driver Number">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="type" class="col-sm-2 pt-2">Type</label>
                    <div class="col-sm-10">
                        <select name="type" id="type" class="form-control">
                            <option value="">Select Ambulance Type</option>
                            @foreach ($types as $type)
                                <option value="{{ $type }}">{{ $type }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row mt-3">
                    <label class="col-sm-2 pt-2"></label>
                    <div class="col-sm-10">
                        <button class="btn btn-success" type="submit">
                            <i class="fa fa-save"></i>  Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection 

resources/views/backend/ambulances/edit.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="container-fluid">  
    <div class="card">
        <div class="card-header">
            <div class="text-center">
                <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Ambulances</span>
            </div>
            <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('ambulances.index')}}">
                <span class="mdi mdi-playlist-plus"> List</span>
            </a>
        </div>
        <div class="card-body">
            <form style="margin-left: 10px" class="form-horizontal" action="{{ route('ambulances.update', $data->id) }}" method="post">
                @method('PUT')
                @csrf 
                <div class="form-group row">
                    <label for="location" class="col-sm-2 pt-2">Locations</label>
                    <div class="col-sm-10">
                        <select name="location_id" class="form-control" required>
                            <option value="">Choose Location</option>
                            @isset($location)
                                @foreach ($location as $item)
                                    <option value="{{ $item->id }}" {{ ($data->location_id == $item->id) ? "selected" : "" }}>
                                        @if(isset($item->division))
                                            {{ isset($item) ? ($item->division.', '.$item->district.', '.$item->area) : null }}
                                        @else                                          
                                            {{ isset($item) ? ($item->district.', '.$item->area) : null }}
                                        @endif
                                    </option>
                                @endforeach
                            @endisset
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="organization_name" class="col-sm-2 pt-2">Organization Name</label>
                    <div class="col-sm-10">
                        <input type="text" id="organization_name" value="{{ $data->organization_name ?? null }}" name="organization_name" class="form-control" placeholder="Enter Organization Name">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="driver_name" class="col-sm-2 pt-2">Driver Name</label>
                    <div class="col-sm-10">
                        <input type="text" id="driver_name" name="driver_name" value="{{ $data->driver_name ?? null }}" class="form-control" placeholder="Enter Driver Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="driver_number" class="col-sm-2 pt-2">Organization Number</label>
                    <div class="col-sm-10">
                        <input type="number" id="driver_number" name="driver_number" value="{{ $data->driver_number ?? null }}" class="form-control" placeholder="Enter Driver Number">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="type" class="col-sm-2 pt-2">Type</label>
                    <div class="col-sm-10">
                        <select name="type" id="type" class="form-control">
                            <option value="">Select Ambulance Type</option>
                            @foreach ($types as $type)
                                <option value="{{ $type }}" {{ ($data->type == $type) ? "selected" : "" }}>
                                    {{ $type }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row mt-3">
                    <label class="col-sm-2 pt-2"></label>
                    <div class="col-sm-10">
                        <button class="btn btn-success" type="submit">
                            <i class="fa fa-save"></i>  Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection 

resources/views/backend/ambulances/index.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header">
            <div class="text-center">
                <span class="m-0 text-info text-center" style="font-size: 30px; margin-right: auto;">Ambulances</span>
            </div>
            <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{ route('ambulances.create') }}">
                <span class="mdi mdi-plus"> Create</span>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="datatable-buttons" class="table table-hover">
                    <thead class="bg-success text-white text-center">
                        <tr class="tableHeader">
                            <th>SL</th>
                            <th>Location</th>
                            <th>Organization Name</th>
                            <th>Driver Name</th>
                            <th>Organization Number</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @isset($ambulances)
                            @foreach ($ambulances as $ambulance)
                                <tr>
                                    <td class="text-center">{{ $loop->iteration }}</td>
                                    <td>
                                        @if(isset($ambulance->location->division))
                                            {{ isset($ambulance->location) ? ($ambulance->location->division.', '.$ambulance->location->district.', '.$ambulance->location->area) : null }}
                                        @else                                          
                                            {{ isset($ambulance->location) ? ($ambulance->location->district.', '.$ambulance->location->area) : null }}
                                        @endif
                                    </td>
                                    <td>{{ $ambulance->organization_name }}</td>
                                    <td>{{ $ambulance->driver_name }}</td>
                                    <td>{{ $ambulance->driver_number }}</td>
                                    <td>{{ $ambulance->type }}</td>
                                    <td class="d-flex justify-content-center">
                                        <a href="{{ route('ambulances.show', $ambulance->id) }}"
                                            class="btn btn-sm btn-outline-info mr-1"><i class="fa fa-eye"></i></a>
                                        <a href="{{ route('ambulances.edit', $ambulance->id) }}"
                                            class="btn btn-sm btn-outline-primary mr-1"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('ambulances.destroy', $ambulance->id) }}" method="post">@csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-outline-danger"
                                                onclick="return confirm('Are You Sure?')"><i
                                                    class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endisset
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/backend/ambulances/show.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="text-center">
                    <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Ambulances</span>
                </div>
                <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('ambulances.index')}}">
                    <span class="mdi mdi-playlist-plus"> List</span>
                </a>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label class="col-sm-2">Location</label>
                    <div class="col-sm-10">
                        {{ $data->location->division . ', ' . $data->location->district . ', ' . $data->location->area }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Organization Name</label>
                    <div class="col-sm-10">
                        {{ $data->organization_name ?? null }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Driver Name</label>
                    <div class="col-sm-10">
                        {{ $data->driver_name ?? null }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Organization Number</label>
                    <div class="col-sm-10">
                        {{ $data->driver_number ?? null }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Ambulance Type</label>
                    <div class="col-sm-10">
                        {{ $data->type ?? null }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection