routes/frontend.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\AmbulanceController;
use App\Http\Controllers\BloodBankController;
use App\Http\Controllers\PoliceStationController;
use App\Models\BloodBank;
use App\Models\Contact;

/* 
/ ------------------------------------------------------------------------
/ Frontend Web Routes Start
/ ------------------------------------------------------------------------
*/

Route::get('/', function () {
    $totalMembers = User::count();
    $donars = BloodBank::count();
    $contacts = Contact::count();
    return view('frontend', compact('totalMembers', 'donars', 'contacts'));
});
Route::get('/contact-us', function () {
    return view('frontend.contact-us');
});

Route::post('sendmail', [ContactController::class, 'sendMail'])->name('sendMail');
Route::get('/contacts', [ContactController::class, 'index'])->name('contact.index');
Route::post('/store', [ContactController::class, 'store'])->name('contact.store');
Route::post('/delete/{id}', [ContactController::class, 'destroy'])->name('contact.delete');


Route::get('/law', function () {
    return view('frontend.law');
});
Route::prefix('services')->group(function () {

    Route::get('/police-stations', [PoliceStationController::class, 'getPoliceStationService']);
    Route::get('/police-stations/{division}', [PoliceStationController::class, 'divisionCategory']);
    Route::get('/get-district', [PoliceStationController::class, 'getDistrict']);
    Route::get('/get-area', [PoliceStationController::class, 'getArea']);
    
    Route::get('/ambulances', [AmbulanceController::class, 'getAmbulanceService']);
    Route::get('/ambulances/{division}', [AmbulanceController::class, 'divisionCategory']);
    Route::get('/blood-bank', [BloodBankController::class, 'getBloodBankService']);
    Route::get('/blood-banks/{division}', [BloodBankController::class, 'divisionCategory']);

    Route::get('/location', [ServicesController::class, 'getGeoLocation']);

    Route::get('/picture-records', function () {
        return view('frontend.services.picture-record');
    });

});

routes/web.php
<?php

use App\Models\User;
use App\Models\Contact;
use App\Models\BloodBank;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\AmbulanceController;
use App\Http\Controllers\BloodBankController;
use App\Http\Controllers\EmergencyController;
use App\Http\Controllers\PictureRecordController;
use App\Http\Controllers\PoliceStationController;
use App\Models\Ambulance;

include('frontend.php');
/* 
/ ------------------------------------------------------------------------
/ Frontend Web Routes End
/ ------------------------------------------------------------------------
*/
Auth::routes(); //[Comments] laravel ui authenticate login routes

Route::middleware(['auth'])->group(function () {
    
    Route::get('/users', [ProfileController::class, 'userList'])->name('users');
    Route::get('/users/edit/{id}', [ProfileController::class, 'userEdit'])->name('user.edit');
    Route::get('profile', [ProfileController::class, 'profile'])->name('profile');
    Route::post('/users/update/{id}', [ProfileController::class, 'userUpdate'])->name('user.update');
    Route::post('update-profile', [ProfileController::class, 'updateProfile'])->name('update-profile');
    Route::post('/destroy/{id}', [ProfileController::class, 'userRemove'])->name('user.destroy');

    /* 
    / ------------------------------------------------------------------------
    / Backend Web Routes Start
    / ------------------------------------------------------------------------
    */

    Route::get('/dashboard', function () {
        $totalMembers = User::count();
        $donars   = BloodBank::count();
        $contacts = Contact::count();
        $ambulances = Ambulance::count();
        return view('backend.dashboard', compact('totalMembers', 'donars', 'contacts', 'ambulances'));
    });

    Route::get('/index', function () {
        return view('backend.application.index');
    });

    Route::resource('locations', LocationController::class);
    Route::resource('police-stations', PoliceStationController::class);
    Route::resource('ambulances', AmbulanceController::class);
    Route::resource('blood-banks', BloodBankController::class);
    
});

Route::post('/emergency-alerts', [EmergencyController::class, 'sendAlert'])->name('emergency-alert');
Route::resource('picture-records', PictureRecordController::class)->except([
    'create', 'show', 'edit', 'update'
]);;

Route::get('locations/{latitude}/{longitude}/{accuracy}', [LocationController::class, 'shareLocation'])->name('share-location');

Route::get('/send-sms', function () {
  
        $sid = "AC1532d12dedb3bb7ec4875aecd73977d6"; // Your Account SID from www.twilio.com/console
        $token = "7331206ec49b58678eba7d77f3f59b97"; // Your Auth Token from www.twilio.com/console

        $client = new Twilio\Rest\Client($sid, $token);
        $message = $client->messages->create(
        '+8801811925439', // Text this number
        [
            'from' => '+18704744277', // From a valid Twilio number
            'body' => 'Hello from Twilio! Prabir'
        ]
        );

    echo  $message->sid;
});





/* 
/ ------------------------------------------------------------------------
/ Backend Web Routes End
/ ------------------------------------------------------------------------
*/



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/PoliceStation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PoliceStation extends Model
{
    use HasFactory;
    protected $table = "police_stations";
    protected $guarded = [];

    public function location()
    {
        return $this->belongsTo(Location::class);
    }
}

app/Http/Controllers/PoliceStationController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\Location;
use Illuminate\Http\Request;
use App\Models\PoliceStation;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;

class PoliceStationController extends Controller
{
    public function index()
    {
        $policeStations = PoliceStation::orderBy('location_id', 'asc')->get();
        return view('backend.police-stations.index', compact('policeStations'));
    }
    public function create()
    {
        $location = Location::all();
        return view('backend.police-stations.create', compact('location'));
    }
    public function store(Request $request)
    {
        try {
            $numbers = explode(',', $request->station_number);
            $policeStation = new PoliceStation();
            $policeStation->location_id    = $request->location_id ?? null;
            $policeStation->name           = $request->name ?? null;
            $policeStation->station_number = json_encode($numbers) ?? null;
            $policeStation->station_tel    = $request->station_tel ?? null;
            $policeStation->description    = $request->description ?? null;
            $policeStation->save();
            
            return redirect()->route('police-stations.index')->with('alert', 'Saved Successfully');
        } 
        catch (Exception $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
    }
    public function show($id)
    {
        $data = PoliceStation::where('id', $id)->first();
        return view('backend.police-stations.show', compact('data'));
    }
    public function edit($id)
    {
        $location = Location::all();
        $data = PoliceStation::where('id', $id)->first();
        return view('backend.police-stations.edit', compact('data', 'location'));
    }
    public function update(Request $request, $id)
    {
        try {
            $numbers = explode(',', $request->station_number);
            $policeStation = PoliceStation::where('id', $id)->first();
            $policeStation->location_id    = $request->location_id ?? null;
            $policeStation->name           = $request->name ?? null;
            $policeStation->station_number = json_encode($numbers) ?? null;
            $policeStation->station_tel    = $request->station_tel ?? null;
            $policeStation->description    = $request->description ?? null;
            $policeStation->save();

            return redirect()->route('police-stations.index')->with('alert', 'Updated Successfully');
        } 
        catch (Exception $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
    }
    public function destroy($id)
    {
        try {
            $data = PoliceStation::where('id', $id)->first();
            $data->delete();
            return redirect()->route('police-stations.index')->with('alert', 'Deleted Successfully');
        } 
        catch (Exception $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->with('alert', $th->getMessage());
        }
    }

    /**
     * FRONTEND INTEGRATION
     */
    public function getPoliceStationService(Request $request)
    {
        try {
            $selectedLocation = $request->location_id ?? null;
            if (isset($request->location_id)) {

                $policeStations = PoliceStation::where('location_id', $request->location_id)->get();
                
            } else {
                $policeStations = PoliceStation::all();
            }
            $locations = Location::orderBy('division', 'asc')->get();
            
            $policeLocations = PoliceStation::pluck('location_id')->toArray();
            $categories = Location::whereIn('id', $policeLocations)->orderBy('division')->get()->groupBy('division');
            
            return view('frontend.services.police-station', compact('policeStations', 'locations', 'selectedLocation', 'categories'));
            
        }
        catch (Exception $th) {
            return redirect()->back()->withErrors($th->getMessage());
        }
        catch (QueryException $th) {
            return redirect()->back()->withErrors($th->getMessage());
        }
    }
    public function divisionCategory($division)
    {
        $locationIds = Location::where(DB::raw(trim('lower(division)', ' ')), 'like', '%' . strtolower($division) . '%')->pluck('id')->toArray();
        $policeStations = PoliceStation::whereIn('location_id', $locationIds)->get();
        $locations = Location::orderBy('division', 'asc')->get();
        $policeLocationIds = PoliceStation::pluck('location_id')->toArray();
        $categories = Location::whereIn('id', $policeLocationIds)->orderBy('division')->get()->groupBy('division');
        return view('frontend.services.police-station', compact('policeStations', 'categories', 'locations'));
    }


    /**
     * API Routes For Locations
     */
    public function getDistrict(Request $request)
    {
        $districts = Location::where("division",$request->division)->pluck("district","id");

        return response()->json($districts);
    }

    public function getArea(Request $request)
    {
        $areas = Location::where("district",$request->district)->pluck("area","id");

        return response()->json($areas);
    }
}

resources/views/backend/police-stations/create.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="container-fluid">  
    <div class="card">
        <div class="card-header">
            <div class="text-center">
                <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Police Station</span>
            </div>
            <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('police-stations.index')}}">
                <span class="mdi mdi-playlist-plus"> List</span>
            </a>
        </div>
        <div class="card-body">
            <form style="margin-left: 10px" class="form-horizontal" action="{{ route('police-stations.store') }}" role="form" method="post">
                @csrf 
                <div class="form-group row">
                    <label for="location" class="col-sm-2 pt-2">Locations</label>
                    <div class="col-sm-10">
                        <select name="location_id" class="form-control" required>
                            <option value="">Choose Location</option>
                            @isset($location)
                                @foreach ($location as $item)
                                    <option value="{{ $item->id }}">
                                        @if(isset($item->division))
                                            {{ isset($item) ? ($item->division.', '.$item->district.', '.$item->area) : null }}
                                        @else                                          
                                            {{ isset($item) ? ($item->district.', '.$item->area) : null }}
                                        @endif
                                    </option>
                                @endforeach
                            @endisset
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 pt-2">Station Name</label>
                    <div class="col-sm-10">
                        <input type="text" id="name" name="name" class="form-control" placeholder="Enter Police Station Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="station_number" class="col-sm-2 pt-2">Station Number</label>
                    <div class="col-sm-10">
                        <input type="text" name="station_number" class="form-control" placeholder="Enter Station Number">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="station_tel" class="col-sm-2 pt-2">Station Tel No</label>
                    <div class="col-sm-10">
                        <input type="text" id="station_tel" name="station_tel" class="form-control" placeholder="Enter Station Tel No">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="description" class="col-sm-2 pt-2">Description</label>
                    <div class="col-sm-10">
                        <textarea name="description" id="description" rows="2" class="form-control" placeholder="Enter Description"></textarea>
                    </div>
                </div>
                <div class="form-group row mt-3">
                    <label class="col-sm-2 pt-2"></label>
                    <div class="col-sm-10">
                        <button class="btn btn-success" type="submit">
                            <i class="fa fa-save"></i>  Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection 

resources/views/backend/police-stations/edit.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="container-fluid">  
    <div class="card">
        <div class="card-header">
            <div class="text-center">
                <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Police Stations</span>
            </div>
            <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('police-stations.index')}}">
                <span class="mdi mdi-playlist-plus"> List</span>
            </a>
        </div>
        <div class="card-body">
            <form style="margin-left: 10px" class="form-horizontal" action="{{ route('police-stations.update', $data->id) }}" method="post">
                @method('PUT')
                @csrf 
                <div class="form-group row">
                    <label for="location" class="col-sm-2 pt-2">Locations</label>
                    <div class="col-sm-10">
                        <select name="location_id" class="form-control" required>
                            <option value="">Choose Location</option>
                            @isset($location)
                                @foreach ($location as $item)
                                    <option value="{{ $item->id }}" {{ ($data->location_id == $item->id) ? "selected" : "" }}>
                                        @if(isset($item->division))
                                            {{ isset($item) ? ($item->division.', '.$item->district.', '.$item->area) : null }}
                                        @else                                          
                                            {{ isset($item) ? ($item->district.', '.$item->area) : null }}
                                        @endif
                                    </option>
                                @endforeach
                            @endisset
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 pt-2">Station Name</label>
                    <div class="col-sm-10">
                        <input type="text" id="name" name="name" value="{{ $data->name ?? null }}" class="form-control" placeholder="Enter Police Station Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="station_number" class="col-sm-2 pt-2">Station Number</label>
                    <div class="col-sm-10" id="police_station_number_div">
                        <input type="text" name="station_number" value="{{ implode(",", json_decode($data->station_number)) ?? null }}" class="form-control" placeholder="Enter Station Number">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="station_tel" class="col-sm-2 pt-2">Station Tel No</label>
                    <div class="col-sm-10">
                        <input type="text" id="station_tel" name="station_tel" value="{{ $data->station_tel ?? null }}" class="form-control" placeholder="Enter Station Tel No">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="description" class="col-sm-2 pt-2">Description</label>
                    <div class="col-sm-10">
                        <textarea name="description" id="description" rows="2" class="form-control" placeholder="Enter Description">{{ $data->description ?? null }}</textarea>
                    </div>
                </div>
                <div class="form-group row mt-3">
                    <label class="col-sm-2 pt-2"></label>
                    <div class="col-sm-10">
                        <button class="btn btn-success" type="submit">
                            <i class="fa fa-save"></i>  Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection 

resources/views/backend/police-stations/index.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header">
        <div class="text-center">
            <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Police Stations</span>
        </div>
        <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('police-stations.create')}}">
            <span class="mdi mdi-plus"> Create</span>
        </a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="datatable-buttons" class="table table-hover">
                <thead class="bg-success text-white text-center">
                   <tr class="tableHeader">
                     <th>SL</th>
                     <th>Location</th>
                     <th>Name</th>
                     <th>Number</th>
                     <th>Tel Number</th>
                     <th>Description</th>
                     <th>Action</th>
                 </tr>
             </thead>
             <tbody>
                @isset($policeStations)
                    @foreach ($policeStations as $policeStation)
                        <tr>
                            <td class="text-center">{{ $loop->iteration }}</td>
                            <td>
                                @if(isset($policeStation->location->division))
                                    {{ isset($policeStation->location) ? ($policeStation->location->division.', '.$policeStation->location->district.', '.$policeStation->location->area) : null }}
                                @else                                          
                                    {{ isset($policeStation->location) ? ($policeStation->location->district.', '.$policeStation->location->area) : null }}
                                @endif                              </td>
                            <td>{{ $policeStation->name }}</td>
                            <td>
                                @isset($policeStation->station_number)
                                    @foreach (json_decode($policeStation->station_number) as $number)                                    
                                        {{ $number }}, 
                                    @endforeach
                                @endisset
                            </td>
                            <td>{{ $policeStation->station_tel }}</td>
                            <td>{{ $policeStation->description }}</td>
                            <td class="d-flex justify-content-center">
                                <a href="{{ route('police-stations.show', $policeStation->id) }}" class="btn btn-sm btn-outline-info mr-1"><i class="fa fa-eye"></i></a>
                                <a href="{{ route('police-stations.edit', $policeStation->id) }}" class="btn btn-sm btn-outline-primary mr-1"><i class="fa fa-edit"></i></a>
                                <form action="{{ route('police-stations.destroy', $policeStation->id) }}" method="post">@csrf @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are You Sure?')"><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endisset
            </tbody>
        </table>
    </div>
</div>
</div>

</div>
@endsection

resources/views/backend/police-stations/show.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="text-center">
                    <span class="m-0 text-info" style="font-size: 30px;text-align: center; margin-right: auto;">Locations</span>
                </div>
                <a class="btn btn-sm btn-outline-success" class="m-0 float-right" href="{{route('police-stations.index')}}">
                    <span class="mdi mdi-playlist-plus"> List</span>
                </a>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label class="col-sm-2">Location</label>
                    <div class="col-sm-10">
                        {{ $data->location->division . ', ' . $data->location->district . ', ' . $data->location->area }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Police Station Name</label>
                    <div class="col-sm-10">
                        {{ $data->name ?? null }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Station Phone Number</label>
                    <div class="col-sm-10">
                        @isset($data->station_number)
                            @foreach (json_decode($data->station_number) as $number)
                                <p>{{ $number }}</p>
                            @endforeach                            
                        @endisset
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Station Tel No</label>
                    <div class="col-sm-10">
                        {{ $data->station_tel ?? null }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2">Description</label>
                    <div class="col-sm-10">
                        {{ $data->description ?? null }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection